version: '3.8'

services:
  webapp:
    # Construye la imagen a partir del Dockerfile en el directorio actual (.)
    build: .
    # Asigna un nombre descriptivo al contenedor
    container_name: pimec-joves-webapp
    # Mapea el puerto 8080 de tu m치quina local al puerto 80 del contenedor
    # donde Nginx est치 escuchando.
    ports:
      - "9999:80"
    # Reinicia el contenedor autom치ticamente si se detiene por alguna raz칩n
    restart: unless-stopped
